# Connect to laminlabs/pertdata

This connects to the LaminDB perturbation instance and shows how to load a
curated AnnData object.

In [1]:
# If needed, install packages (uncomment):
# %pip install lamindb bionty pertdata
# %lamin init --storage ./pertdata --modules bionty,pertdata
import lamindb as ln
import bionty as bt

db = ln.DB("laminlabs/pertdata")

→ connected lamindb: jkobject/scperturb

In [2]:
collection = db.Collection.filter(key="pertdata_datasets").one()

In [29]:
import sys
sys.path.append("../")
from tools.preprocess_collection import *
from tools.preprocess_lincs import connect_databases, plan_lincs_aggregation, aggregate_lincs
%reload_ext autoreload
%autoreload 2

In [22]:
schema = find_schema(schema_uid=None, schema_name=None)

In [25]:
artifacts_all = list(db.Artifact.filter().all())
len(artifacts_all)

411

In [ ]:
artifacts = latest_by_key([a for a in artifacts_all if a.key])
len(artifacts)

332

In [ ]:
for i in db.Artifact.filter(key__contains="README.md").all():
    print(i.cache())

! run input wasn't tracked, call `ln.track()` and re-run
/Users/jkobject/Library/Caches/lamindb/arc-ctc-tahoe100/tahoe100m/2025-02-25/README.md
... synchronizing rPd3AmzfmA6w9sVd0006.md: 100.0%
! run input wasn't tracked, call `ln.track()` and re-run
/Users/jkobject/Library/Caches/lamindb/lamin-us-west-2/H7d9vxvceBoh/.lamindb/rPd3AmzfmA6w9sVd0006.md
... synchronizing rPd3AmzfmA6w9sVd0000.md: 100.0%
! run input wasn't tracked, call `ln.track()` and re-run
/Users/jkobject/Library/Caches/lamindb/lamin-us-west-2/H7d9vxvceBoh/.lamindb/rPd3AmzfmA6w9sVd0000.md
... synchronizing rPd3AmzfmA6w9sVd0005.md: 100.0%
! run input wasn't tracked, call `ln.track()` and re-run
/Users/jkobject/Library/Caches/lamindb/lamin-us-west-2/H7d9vxvceBoh/.lamindb/rPd3AmzfmA6w9sVd0005.md
... synchronizing README.md: 100.0%
! run input wasn't tracked, call `ln.track()` and re-run
/Users/jkobject/Library/Caches/lamindb/lamin-us-west-2/H7d9vxvceBoh/README.md
... synchronizing rPd3AmzfmA6w9sVd0003.md: 100.0%
! run input wasn't tracked, call `ln.track()` and re-run
/Users/jkobject/Library/Caches/lamindb/lamin-us-west-2/H7d9vxvceBoh/.lamindb/rPd3AmzfmA6w9sVd0003.md
... synchronizing GSE305370_README.md.txt: 100.0%
! run input wasn't tracked, call `ln.track()` and re-run
/Users/jkobject/Library/Caches/lamindb/ftp.ncbi.nlm.nih.gov/cellarity/GSE305370/GSE305370_README.md.txt
... synchronizing rPd3AmzfmA6w9sVd0002.md: 100.0%
! run input wasn't tracked, call `ln.track()` and re-run
/Users/jkobject/Library/Caches/lamindb/lamin-us-west-2/H7d9vxvceBoh/.lamindb/rPd3AmzfmA6w9sVd0002.md
... synchronizing rPd3AmzfmA6w9sVd0001.md: 100.0%
! run input wasn't tracked, call `ln.track()` and re-run
/Users/jkobject/Library/Caches/lamindb/lamin-us-west-2/H7d9vxvceBoh/.lamindb/rPd3AmzfmA6w9sVd0001.md
... synchronizing rPd3AmzfmA6w9sVd0004.md: 100.0%
! run input wasn't tracked, call `ln.track()` and re-run
/Users/jkobject/Library/Caches/lamindb/lamin-us-west-2/H7d9vxvceBoh/.lamindb/rPd3AmzfmA6w9sVd0004.md

In [157]:
df = db.Artifact.get(key="df_all__efo__3.80.0__ExperimentalFactor.parquet").load()

... synchronizing df_all__efo__3.80.0__ExperimentalFactor.parquet: 100.0%
! run input wasn't tracked, call `ln.track()` and re-run

In [158]:
df

,name,definition,synonyms,parents
ontology_id,,,,
EFO:0000001,experimental factor,An Experimental Factor In Array Express Which ...,ExperimentalFactor,[]
EFO:0000002,CS57511,Cs57511 Is An Arabidopsis Thaliana Strain As D...,None,[]
EFO:0000003,CS57512,Cs57512 Is An Arabidopsis Thaliana Strain As D...,None,[]
EFO:0000004,CS57515,Cs57515 Is An Arabidopsis Thaliana Strain As D...,None,[]
EFO:0000005,CS57520,Cs57520 Is An Arabidopsis Thaliana Strain As D...,None,[]
...,...,...,...,...
EFO:1002047,spotted fever,A Type Of Tick-Borne Disease Which Presents On...,spotted fever|spotted fever rickettsiae diseas...,[EFO:1001128]
EFO:1002048,kidney failure,An Acute Or Chronic Condition That Is Characte...,"renal insufficiency|failure, renal|kidney fail...",[EFO:0003086]
EFO:1002049,glomerular disease,A Disease Involving The Renal Glomerulus.,disease of renal glomerulus|renal glomerulus d...,[EFO:0003086]
EFO:1002050,nephritis,Inflammation Of Renal Tissue.,nephritis|inflammation of kidney|kidney inflam...,"[EFO:0009903, EFO:0003086]"
EFO:1002051,facial nerve disease,A Disease Involving The Facial Nerve.,disorder of facial nerve|facial nerve disease ...,[EFO:0009387]

In [ ]:
unprocessed = [
    # GSE81884
    "scperturb/records/13350497/files/XieHon2017.h5ad",
    "scperturb/records/13350497/files/PapalexiSatija2021_eccite_arrayed_RNA.h5ad",
    "scperturb/records/13350497/files/PapalexiSatija2021_eccite_arrayed_protein.h5ad",
    "scperturb/records/13350497/files/PapalexiSatija2021_eccite_protein.h5ad",
    "scperturb/records/13350497/files/PapalexiSatija2021_eccite_RNA.h5ad",
    #
    "scperturb/records/13350497/files/GehringPachter2019.h5ad",
    # GSE106340 , GSE115943
    "scperturb/records/13350497/files/SchiebingerLander2019_GSE115943.h5ad",
    "scperturb/records/13350497/files/SchiebingerLander2019_GSE106340.h5ad",
    # GSE120861
    "scperturb/records/13350497/files/GasperiniShendure2019_atscale.h5ad",
    "scperturb/records/13350497/files/GasperiniShendure2019_highMOI.h5ad",
    "scperturb/records/13350497/files/GasperiniShendure2019_lowMOI.h5ad",
    "parse10m/Parse_10M_PBMC_cytokines",
]

others = [
    "scperturb/sunshine23",
    "scperturb/shifrut18",  # GSE119450
    "DRUG-seq/GSE120222",
    "scperturb/chang22",  # changye2021
    "scperturb/aissa21",  # GSE149383
    "scperturb/datlinger17",  # GSE92872
    "scperturb/datlinger21",  # GSE168620
    "scperturb/frangieh21",
    "scperturb/xu23",
    "scperturb/wessels22",
    "scperturb/zhao21",  # GSE148842
    # GSE124703
    "scperturb/tian21_CRISPRi",
    "scperturb/tian21_CRISPRa",
    # GSE153056
    "scperturb/papalexi21_eccite_arrayed_RNA",
    "scperturb/papalexi21_eccite_RNA",
    # GSE152988
    "scperturb/tian19_day7neuron",
    "scperturb/tian19_iPSC",
    "scperturb/norman19",  # GSE133344
    "scperturb/mcfarland20",
    "ginkgo-datapoints/vcpi",
]

# add gene effect and other features for mcfarland20
# redo the parse10m to follow the same schema as the others

srivatsan = [  # GSE139944
    "scperturb/srivatsan20_sciplex2",
    "scperturb/srivatsan20_sciplex3",
    "scperturb/srivatsan20_sciplex4",
]

# could be merged

gwps = [
    "scperturb/replogle22_K562_gwps",
    "scperturb/replogle22_RPE1",
    # "scperturb/replogle22_K562_essential",
]

adamson = [
    "scperturb/adamson16_GSM2406675_10X001",  # GSE90546
    "scperturb/adamson16_GSM2406677_10X005",
    "scperturb/adamson16_GSM2406681_10X010",
]

# could be merged

nadig = ["scperturb/nadig24_hepg2", "scperturb/nadig24_jurkat"]

# could be merged

dixit = [
    "scperturb/dixit16_K562_TFs_13_days",  # GSE90063
    "scperturb/dixit16_K562_TFs_7_days",
    "scperturb/dixit16_K562_TFs_High_MOI",
]

# could be merged

lincs = [
    # "lincs/phase1/Level2_GEX_delta_n49216x978",
    "lincs/phase1/Level2_GEX_epsilon_n1269922x978",
    "lincs/phase2/Level2_GEX_all_n537590x978",
]
# remaining add lincs Level4 data

tahoe = [
    # "tahoe100m/Tahoe-100M-SCVI-v1/minified_AnnData",
    "tahoe100m/2025-02-25/plate1_filt_Vevo_Tahoe100M_WServicesFrom_ParseGigalab",
    "tahoe100m/2025-02-25/plate2_filt_Vevo_Tahoe100M_WServicesFrom_ParseGigalab",
    "tahoe100m/2025-02-25/plate3_filt_Vevo_Tahoe100M_WServicesFrom_ParseGigalab",
    "tahoe100m/2025-02-25/plate4_filt_Vevo_Tahoe100M_WServicesFrom_ParseGigalab",
    "tahoe100m/2025-02-25/plate5_filt_Vevo_Tahoe100M_WServicesFrom_ParseGigalab",
    "tahoe100m/2025-02-25/plate6_filt_Vevo_Tahoe100M_WServicesFrom_ParseGigalab",
    "tahoe100m/2025-02-25/plate7_filt_Vevo_Tahoe100M_WServicesFrom_ParseGigalab",
    "tahoe100m/2025-02-25/plate8_filt_Vevo_Tahoe100M_WServicesFrom_ParseGigalab",
    "tahoe100m/2025-02-25/plate9_filt_Vevo_Tahoe100M_WServicesFrom_ParseGigalab",
    "tahoe100m/2025-02-25/plate10_filt_Vevo_Tahoe100M_WServicesFrom_ParseGigalab",
    "tahoe100m/2025-02-25/plate11_filt_Vevo_Tahoe100M_WServicesFrom_ParseGigalab",
    "tahoe100m/2025-02-25/plate12_filt_Vevo_Tahoe100M_WServicesFrom_ParseGigalab",
    "tahoe100m/2025-02-25/plate13_filt_Vevo_Tahoe100M_WServicesFrom_ParseGigalab",
    "tahoe100m/2025-02-25/plate14_filt_Vevo_Tahoe100M_WServicesFrom_ParseGigalab",
]

GSE305979 = [
    "cellarity/GSE305979/GSE305979_day0_raw_counts",
    "cellarity/GSE305979/GSE305979_day1-7_raw_counts",
    "cellarity/GSE305979/GSE305979_day0-7_normalized_counts_with_celltype_annotations",
]

# why does GSE305979_day0-7_normalized_counts contains less cells than the raw counts? maybe some filtering was done?

GSE306429 = [
    "cellarity/GSE306429/GSE306429_combined_vscores",
    "cellarity/GSE306429/GSE306429_combined_demuxed",
]


# GSE305370 = [
#    "cellarity/GSE305370/GSE305370_multiome_alldonors_alldays",
#    "cellarity/GSE305370/GSE305370_citeseq_alldonors_alldays",
# ]
# merge cite and multiome

# compute diff expr (parquet) for all datasets

# check missing annotations (overlap of obs features and unknown or empty fields)

# preprocess by computing quality metrics (mito, ribo, etc) and flagging low quality cells

# compute and find missing annotations (sex, ethnicity, pert library)

# define fingerprints for all datasets (perturbation, cell type, etc)

# get the dna seq for all patients

# compute an embedding (obsm)

In [117]:
for i in db.Artifact.filter(key__contains="parse10m"):
    print(i.key)

parse10m/Parse_10M_PBMC_cytokines_curated.tiledbsoma
parse10m/Parse_10M_PBMC_cytokines.h5ad

In [132]:
obs_artifact = db.Artifact.get(key=GSE306429[1] + "/obs.parquet")
obs_artifact.n_observations, obs_artifact.features

Artifact: cellarity/GSE306429/GSE306429_combined_demuxed/obs.parquet (0000)
├── Dataset features
│   └── columns (11)
│       assay                          bionty.ExperimentalFactor            10x 3' v3
│       cell_line                      bionty.CellLine                      A-375, A549, CD34+, CD8+, HA1E cell, H…
│       organism                       bionty.Organism                      human
│       pert_compound                  pertdb.Compound
│       pert_compound_multi            list[pertdb.Compound]
│       pert_dose                      str
│       pert_name                      str
│       pert_time                      str
│       pert_type                      ULabel[380pmYI1]                     compound
│       suspension_type                ULabel[je7xSS9z]                     cell
│       tissue_type                    ULabel[FzEcREBL]                     cell culture
└── External features
    └── X                              Artifact                             cellarity/GSE306429/GSE306429_combined…

(1257778, )

In [ ]:
obs_artifact = db.Artifact.get(
    key="lincs/phase1/Level2_GEX_delta_n49216x978/obs.parquet"
)

In [133]:
obs_artifact

Artifact(uid='DWsyQzOmlTS19kUr0000', version_tag=None, is_latest=True, key='cellarity/GSE306429/GSE306429_combined_demuxed/obs.parquet', description=None, suffix='.parquet', kind='dataset', otype='DataFrame', size=12051619, hash='qWquoJjIzx0wuEUGN2h6rg', n_files=None, n_observations=1257778, branch_id=1, created_on_id=1, space_id=1, storage_id=1, run_id=87, schema_id=37, created_by_id=1, created_at=2025-11-13 18:57:39 UTC, is_locked=False)

In [ ]:
# MODEL
obs_artifact = db.Artifact.get(
    key="lincs/phase1/Level2_GEX_delta_n49216x978/obs.parquet"
)
X_artifact = obs_artifact.features.get_values()["X"]
var_artifact = X_artifact.features.get_values()["var"]

adata = X_artifact.load()
adata.obs = obs_artifact.load()
adata.var = var_artifact.load()

In [ ]:
# doing lincs
for art in artifacts:
    if art.key.startswith("lincs"):
        print(art.key)

In [ ]:
scperturb / records / 13350497 / files / GasperiniShendure2019_atscale.h5ad
scperturb / records / 13350497 / files / GasperiniShendure2019_highMOI.h5ad
scperturb / records / 13350497 / files / GasperiniShendure2019_lowMOI.h5ad

In [ ]:
elem = [
    "ZhaoSims2021",
    "ChangYe",
    "ShifrutMarson2018",
    "SchiebingerLander2019",
    "XieHon2017",
    "XuCao2023",
    "PapalexiSatija2021",
    "GehringPachter2019",
    "GasperiniShendure2019",
    "sanja",
]

In [152]:
# doing lincs
for art in artifacts:
    if any(e in art.key for e in elem):
        print(art.key)

scperturb/records/13350497/files/GasperiniShendure2019_atscale.h5ad
scperturb/records/13350497/files/GasperiniShendure2019_highMOI.h5ad
scperturb/records/13350497/files/ZhaoSims2021.h5ad
scperturb/records/13350497/files/ChangYe2021.h5ad
scperturb/records/13350497/files/ShifrutMarson2018.h5ad
scperturb/records/13350497/files/SchiebingerLander2019_GSE106340.h5ad
scperturb/records/13350497/files/XieHon2017.h5ad
scperturb/records/13350497/files/PapalexiSatija2021_eccite_arrayed_RNA.h5ad
scperturb/records/13350497/files/PapalexiSatija2021_eccite_arrayed_protein.h5ad
scperturb/records/13350497/files/PapalexiSatija2021_eccite_protein.h5ad
scperturb/records/13350497/files/GasperiniShendure2019_lowMOI.h5ad
scperturb/records/13350497/files/GehringPachter2019.h5ad
scperturb/records/13350497/files/SchiebingerLander2019_GSE115943.h5ad
scperturb/records/13350497/files/XuCao2023.h5ad
scperturb/records/13350497/files/PapalexiSatija2021_eccite_RNA.h5ad

In [ ]:
db.Artifact.filter().to_dataframe(limit=None)[
    db.Artifact.filter().to_dataframe(limit=None).key.str.split("/").str[1]
    == "2025-02-25"
]

,uid,key,description,suffix,kind,otype,size,hash,n_files,n_observations,...,is_latest,is_locked,created_at,branch_id,created_on_id,space_id,storage_id,run_id,schema_id,created_by_id
id,,,,,,,,,,,,,,,,,,,,,
246,cValvuqVvKDY5T8b0000,tahoe100m/2025-02-25/var.parquet,None,.parquet,dataset,DataFrame,1324368,f07nmZqAIFW6HUFxjNEvXA,NaN,62710.0,...,True,False,2025-07-23 18:14:21.512878+00:00,1,1,1,1,74.0,NaN,1
243,uOpawMuv6DnVIadP0000,tahoe100m/2025-02-25/plate14_filt_Vevo_Tahoe10...,Curated obs metadata for plate14,.parquet,dataset,DataFrame,221062501,OoGv4itI-8kXSdOkQxELwP,NaN,6518806.0,...,True,False,2025-07-23 15:37:44.967264+00:00,1,1,1,1,69.0,37.0,1
242,h8ML2WwxUgdT8Cn10000,tahoe100m/2025-02-25/plate13_filt_Vevo_Tahoe10...,Curated obs metadata for plate13,.parquet,dataset,DataFrame,290822142,0Rkkwhkm2cJmz9IrgK8-aC,NaN,8501658.0,...,True,False,2025-07-23 15:33:09.168727+00:00,1,1,1,1,69.0,37.0,1
241,sTKrKPpB5QpIV4iH0000,tahoe100m/2025-02-25/plate12_filt_Vevo_Tahoe10...,Curated obs metadata for plate12,.parquet,dataset,DataFrame,353120964,Ld7bu04sX_LzPp1OwLD_H6,NaN,10487057.0,...,True,False,2025-07-23 15:27:01.332911+00:00,1,1,1,1,69.0,37.0,1
240,sYsONFIQvd9Sh46U0000,tahoe100m/2025-02-25/plate11_filt_Vevo_Tahoe10...,Curated obs metadata for plate11,.parquet,dataset,DataFrame,248266928,g_V_jJ-LmzBwLpR6ZuO1eS,NaN,7435869.0,...,True,False,2025-07-23 15:20:43.017355+00:00,1,1,1,1,69.0,37.0,1
239,g8cnCPc2YwD9vfg60000,tahoe100m/2025-02-25/plate10_filt_Vevo_Tahoe10...,Curated obs metadata for plate10,.parquet,dataset,DataFrame,273754401,9pHavAy69ENT7tCxNMaoLr,NaN,8044908.0,...,True,False,2025-07-23 15:15:10.476688+00:00,1,1,1,1,69.0,37.0,1
238,PQSIhkmWMi38Ox620000,tahoe100m/2025-02-25/plate9_filt_Vevo_Tahoe100...,Curated obs metadata for plate9,.parquet,dataset,DataFrame,197518675,pEjeYLb-Tb54qOqfhp6J__,NaN,5866669.0,...,True,False,2025-07-23 15:07:50.408485+00:00,1,1,1,1,69.0,37.0,1
237,l0bOjTZKXiV8nmlH0000,tahoe100m/2025-02-25/plate8_filt_Vevo_Tahoe100...,Curated obs metadata for plate8,.parquet,dataset,DataFrame,303889166,SgRcAc8UKsb-TqYs7-QJbb,NaN,8880979.0,...,True,False,2025-07-23 15:03:23.922311+00:00,1,1,1,1,69.0,37.0,1
236,PUBDwkCFl6mdOTYr0000,tahoe100m/2025-02-25/plate7_filt_Vevo_Tahoe100...,Curated obs metadata for plate7,.parquet,dataset,DataFrame,190770986,8M1vnMaIoAmM9WL52tZq9U,NaN,5692117.0,...,True,False,2025-07-23 13:50:51.218020+00:00,1,1,1,1,69.0,37.0,1
235,IOuGOf4GPc9KVBgi0000,tahoe100m/2025-02-25/plate6_filt_Vevo_Tahoe100...,Curated obs metadata for plate6,.parquet,dataset,DataFrame,259733321,OqI0Pg1MRuyedHJB6crEBs,NaN,7545393.0,...,True,False,2025-07-23 13:43:45.291639+00:00,1,1,1,1,69.0,37.0,1
234,rQMqaImEQpXVJIwD0000,tahoe100m/2025-02-25/plate5_filt_Vevo_Tahoe100...,Curated obs metadata for plate5,.parquet,dataset,DataFrame,216015885,HX0ncmf69sdkW9AnbR844A,NaN,6419498.0,...,True,False,2025-07-23 13:38:43.232104+00:00,1,1,1,1,69.0,37.0,1
233,6SHCMwyJFbvNgvqI0000,tahoe100m/2025-02-25/plate4_filt_Vevo_Tahoe100...,Curated obs metadata for plate4,.parquet,dataset,DataFrame,234695583,ttbVGh9fNkP0lXnLrAlBHQ,NaN,7004356.0,...,True,False,2025-07-23 13:33:46.546828+00:00,1,1,1,1,69.0,37.0,1
232,o4c0PJ1lB02QwLBj0000,tahoe100m/2025-02-25/plate3_filt_Vevo_Tahoe100...,Curated obs metadata for plate3,.parquet,dataset,DataFrame,156216650,7ul2fY4euY2ifrSjVkR6Gt,NaN,4705402.0,...,True,False,2025-07-23 13:25:42.613389+00:00,1,1,1,1,69.0,37.0,1
231,TG9hJgIdaY8gKNe80000,tahoe100m/2025-02-25/plate2_filt_Vevo_Tahoe100...,Curated obs metadata for plate2,.parquet,dataset,DataFrame,272012731,YAdkM1yKR_r_F0QvjaZW5B,NaN,8064658.0,...,True,False,2025-07-23 13:21:53.981840+00:00,1,1,1,1,69.0,37.0,1
230,BkGlVEce52rFQS5l0000,tahoe100m/2025-02-25/plate1_filt_Vevo_Tahoe100...,Curated obs metadata for plate1,.parquet,dataset,DataFrame,183737105,j8wjq5Pl5VKFuNrrPgrXbS,NaN,5481420.0,...,True,False,2025-07-23 13:05:43.471170+00:00,1,1,1,1,69.0,37.0,1
220,BDttiuV3Te8VB0dU0000,tahoe100m/2025-02-25/plate9_filt_Vevo_Tahoe100...,None,.h5ad,dataset,AnnData,18791302576,4kHbVbmreg6akW6ZgsjxaA,NaN,5866669.0,...,True,False,2025-02-25 23:22:22.759201+00:00,1,1,1,8,67.0,NaN,1
219,ZFeVfd0ugAHeWCxm0000,tahoe100m/2025-02-25/plate2_filt_Vevo_Tahoe100...,None,.h5ad,dataset,AnnData,29037152127,usxviuqGbuw0RYnECCVCWw,NaN,8064658.0,...,True,False,2025-02-25 23:22:20.113956+00:00,1,1,1,8,67.0,NaN,1
218,omn7JStfJMzy8m6O0000,tahoe100m/2025-02-25/plate11_filt_Vevo_Tahoe10...,None,.h5ad,dataset,AnnData,23230802756,N2mzoYlMLEl6PdecaYyDvw,NaN,7435869.0,...,True,False,2025-02-25 23:22:18.229629+00:00,1,1,1,8,67.0,NaN,1
217,czC19UpUEszVH2bU0000,tahoe100m/2025-02-25/plate8_filt_Vevo_Tahoe100...,None,.h5ad,dataset,AnnData,30390935958,ilAzEPIh4FlDeTFaJ1dILw,NaN,8880979.0,...,True,False,2025-02-25 23:22:22.387666+00:00,1,1,1,8,67.0,NaN,1
216,wadBkVuZ2yOOIrKa0000,tahoe100m/2025-02-25/metadata/sample_metadata....,None,.parquet,dataset,DataFrame,65636,vLYHp68bvPlKpXJusezDXA,NaN,1344.0,...,True,False,2025-02-25 19:33:43.178496+00:00,1,1,1,8,67.0,NaN,1
215,aJIqo7bNyJAs9z0r0000,tahoe100m/2025-02-25/plate1_filt_Vevo_Tahoe100...,None,.h5ad,dataset,AnnData,19070623904,9iCNcouMqfNS3HA/2GUWOA,NaN,5481420.0,...,True,False,2025-02-25 23:22:19.737995+00:00,1,1,1,8,67.0,NaN,1
214,tKTeff0ugWqAm4P70000,tahoe100m/2025-02-25/plate4_filt_Vevo_Tahoe100...,None,.h5ad,dataset,AnnData,23292672278,BkBXznbSovNWXtzPFITPcQ,NaN,7004356.0,...,True,False,2025-02-25 23:22:20.879928+00:00,1,1,1,8,67.0,NaN,1
213,aAHQ3zbD7n1asyYr0000,tahoe100m/2025-02-25/plate6_filt_Vevo_Tahoe100...,None,.h5ad,dataset,AnnData,28934897078,NYvQEqVClziHm0ozWhOw1w,NaN,7545393.0,...,True,False,2025-02-25 23:22:21.629962+00:00,1,1,1,8,67.0,NaN,1
212,EZATJLC4jE7pmwo40000,tahoe100m/2025-02-25/plate5_filt_Vevo_Tahoe100...,None,.h5ad,dataset,AnnData,19763140865,VMBKFzOI5cj7UC1UDENP4A,NaN,6419498.0,...,True,False,2025-02-25 23:22:21.255154+00:00,1,1,1,8,67.0,NaN,1
211,S2h2rPLCaUhZAM9u0000,tahoe100m/2025-02-25/plate12_filt_Vevo_Tahoe10...,None,.h5ad,dataset,AnnData,37495736876,VjAkWVFGVpzAMi9Innusuw,NaN,10487057.0,...,True,False,2025-02-25 23:22:18.600910+00:00,1,1,1,8,67.0,NaN,1
210,DC5cacdJr1VoEXnl0000,tahoe100m/2025-02-25/plate7_filt_Vevo_Tahoe100...,None,.h5ad,dataset,AnnData,16514746341,NOS4MY6eYYPOnAB8ViyWYg,NaN,5692117.0,...,True,False,2025-02-25 23:22:22.009157+00:00,1,1,1,8,67.0,NaN,1
209,9L9HZ55HqUL0aqaR0000,tahoe100m/2025-02-25/plate13_filt_Vevo_Tahoe10...,None,.h5ad,dataset,AnnData,28071589885,RKOiaay+CHvv+Ukk/N+28A,NaN,8501658.0,...,True,False,2025-02-25 23:22:18.977981+00:00,1,1,1,8,67.0,NaN,1
208,vn5cUJCHbjpPPsZx0000,tahoe100m/2025-02-25/plate14_filt_Vevo_Tahoe10...,None,.h5ad,dataset,AnnData,22427932564,FrnStRehP16siRGG35ou+g,NaN,6518806.0,...,True,False,2025-02-25 23:22:19.357999+00:00,1,1,1,8,67.0,NaN,1
207,mUHMY4vxqnxMOclK0000,tahoe100m/2025-02-25/README.md,None,.md,None,None,368,aiKFGBEFe3VV6TLBIA3kyg,NaN,NaN,...,True,False,2025-02-25 19:31:29.489283+00:00,1,1,1,8,67.0,NaN,1
206,3Yl20zyG926CkvP50000,tahoe100m/2025-02-25/tutorial/plate3_2k-obs/X....,None,.h5ad,dataset,AnnData,7253540,vv16qryJsVY98jDBqhkr9w,NaN,2000.0,...,True,False,2025-02-25 19:31:01.255128+00:00,1,1,1,8,67.0,NaN,1
205,sxABPJYQPo3koqmN0000,tahoe100m/2025-02-25/metadata/obs_metadata_des...,None,.tsv,None,DataFrame,879,HBFLKDzsJzok7ONs0mRtEw,NaN,17.0,...,True,False,2025-02-25 19:33:42.909050+00:00,1,1,1,8,67.0,NaN,1
204,56uA9lPPmJ4zLUcr0000,tahoe100m/2025-02-25/plate10_filt_Vevo_Tahoe10...,None,.h5ad,dataset,AnnData,26536400717,j1FXsX7hs7u+eBqnWnmNHw,NaN,8044908.0,...,True,False,2025-02-25 23:22:17.849980+00:00,1,1,1,8,67.0,NaN,1
203,XVSrkq9pyF1OBLgG0000,tahoe100m/2025-02-25/plate3_filt_Vevo_Tahoe100...,None,.h5ad,dataset,AnnData,13173722269,Jnrt7DaSUCGn8D8LS2itaw,NaN,4705402.0,...,True,False,2025-02-25 23:22:20.497965+00:00,1,1,1,8,67.0,NaN,1
202,y1TTR9wbrmZEwpOa0000,tahoe100m/2025-02-25/metadata/obs_metadata.par...,None,.parquet,dataset,DataFrame,2293981573,qEWOpGw9CmQVzaElyMWT1Q,NaN,100648790.0,...,True,False,2025-02-25 19:33:42.721038+00:00,1,1,1,8,67.0,NaN,1

In [ ]:
set(db.Artifact.filter().to_dataframe(limit=None).key.str.split("/").str[1])

{'2025-02-25',
 'GSE120222',
 'GSE305370',
 'GSE305979',
 'GSE306429',
 'GSE70138',
 'GSE92742',
 'Parse_10M_PBMC_cytokines.h5ad',
 'Parse_10M_PBMC_cytokines_curated.tiledbsoma',
 'Tahoe-100M-SCVI-v1',
 'adamson16_GSM2406675_10X001',
 'adamson16_GSM2406677_10X005',
 'adamson16_GSM2406681_10X010',
 'aissa21',
 'cell_line_metadata.parquet',
 'chang22',
 'datlinger17',
 'datlinger21',
 'dixit16_K562_TFs_13_days',
 'dixit16_K562_TFs_7_days',
 'dixit16_K562_TFs_High_MOI',
 'frangieh21',
 'geneinfo.parquet',
 'mcfarland20',
 'mock_model_scvi.pt',
 'model.pt',
 'nadig24_hepg2',
 'nadig24_jurkat',
 nan,
 'norman19',
 'papalexi21_eccite_RNA',
 'papalexi21_eccite_arrayed_RNA',
 'phase1',
 'phase2',
 'records',
 'replogle22_K562_essential',
 'replogle22_K562_gwps',
 'replogle22_RPE1',
 'shifrut18',
 'srivatsan20_sciplex2',
 'srivatsan20_sciplex3',
 'srivatsan20_sciplex4',
 'sunshine23',
 'tahoe100',
 'tian19_day7neuron',
 'tian19_iPSC',
 'tian21_CRISPRa',
 'tian21_CRISPRi',
 'vcpi',
 'wessels22',
 'xu23',
 'zhao21'}

In [ ]:
nadig24
aissa21
vcpi
replogle
dixit16
GSE1200
zhao21
xu23
wessels22
tian21
tian19
srivatsan20
mcfarland20

In [ ]:
db.bionty.Organism.filter().to_dataframe(limit=None)

,uid,name,ontology_id,abbr,synonyms,description,scientific_name,is_locked,created_at,branch_id,space_id,created_by_id,run_id,source_id
id,,,,,,,,,,,,,,
2,3RZqbcSLWNGQGZ,mouse,NCBITaxon:10090,None,None,None,Mus musculus,False,2025-01-10 09:10:26.654102+00:00,1,1,1,1,1
1,1dpCL6TduFJ3AP,human,NCBITaxon:9606,None,None,None,Homo sapiens,False,2025-01-10 09:09:31.662158+00:00,1,1,1,1,1

In [ ]:
db.bionty.Gene.filter().to_dataframe(limit=None)

,uid,abbr,synonyms,description,symbol,stable_id,ensembl_gene_id,ncbi_gene_ids,biotype,is_locked,created_at,branch_id,space_id,created_by_id,run_id,source_id,organism_id
id,,,,,,,,,,,,,,,,,
132480,4s1Zf4HuctP7KS,None,None,None,None,None,ENSG00000284737,None,None,False,2025-01-17 07:14:19.138328+00:00,1,1,1,51,NaN,1
132479,60sc1BU8AnSk4S,None,None,None,None,None,ENSG00000284714,None,None,False,2025-01-17 07:14:19.138328+00:00,1,1,1,51,NaN,1
132478,64l1gcpbVwxujl,None,None,None,None,None,ENSG00000284683,None,None,False,2025-01-17 07:14:19.138328+00:00,1,1,1,51,NaN,1
132477,6dmaRYJ3K9FA0J,None,None,None,None,None,ENSG00000284561,None,None,False,2025-01-17 07:14:19.138328+00:00,1,1,1,51,NaN,1
132476,5TKpJ4YHvun1Ye,None,None,None,None,None,ENSG00000284486,None,None,False,2025-01-17 07:14:19.138328+00:00,1,1,1,51,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5,3wEqb6eOTZzC42,None,C1ORF112|FLJ10706|APOLO1|FLIP|MEICA1,FIGNL1 interacting regulator of recombination ...,FIRRM,None,ENSG00000000460,55732,protein_coding,False,2025-01-10 09:09:58.273264+00:00,1,1,1,1,11.0,1
4,5Zug63FETk4pJF,None,PACE1|PACE-1,SCY1 like pseudokinase 3,SCYL3,None,ENSG00000000457,57147,protein_coding,False,2025-01-10 09:09:58.273239+00:00,1,1,1,1,11.0,1
3,4eC1wUNJAO2s7T,None,CDGIE|MPDS,dolichyl-phosphate mannosyltransferase subunit...,DPM1,None,ENSG00000000419,8813,protein_coding,False,2025-01-10 09:09:58.273204+00:00,1,1,1,1,11.0,1
2,2FhduD7Z97Uvq1,None,TEM|MYODULIN|CHM1L|TENDIN|BRICD4,tenomodulin,TNMD,None,ENSG00000000005,64102,protein_coding,False,2025-01-10 09:09:58.273178+00:00,1,1,1,1,11.0,1
1,1uTi9dROoaN5rR,None,TSPAN-6|T245|TM4SF6,tetraspanin 6,TSPAN6,None,ENSG00000000003,7105,protein_coding,False,2025-01-10 09:09:58.273110+00:00,1,1,1,1,11.0,1